-- MySQL Script generated by MySQL Workbench
-- Fri Jun 12 17:19:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lecture_forum
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lecture_forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lecture_forum` DEFAULT CHARACTER SET utf8 ;
USE `lecture_forum` ;

-- -----------------------------------------------------
-- Table `lecture_forum`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lecture_forum`.`users` (
  `UserID` INT(11) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lecture_forum`.`threads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lecture_forum`.`threads` (
  `UserID` INT(11) NOT NULL,
  `ThreadID` INT(11) NOT NULL AUTO_INCREMENT,
  `thread_summary` LONGTEXT NOT NULL,
  `thread_description` LONGTEXT NOT NULL,
  `Replies` INT(11) NULL DEFAULT '0',
  `Attachment` BLOB NULL DEFAULT NULL,
  `date_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ThreadID`),
  INDEX `user_thread_idx` (`UserID` ASC),
  CONSTRAINT `user_thread`
    FOREIGN KEY (`UserID`)
    REFERENCES `lecture_forum`.`users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lecture_forum`.`replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lecture_forum`.`replies` (
  `reply_text` LONGTEXT NULL DEFAULT NULL,
  `Attachment` BLOB NULL DEFAULT NULL,
  `ThreadID` INT(11) NULL DEFAULT NULL,
  `date_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UserID` INT(11) NULL DEFAULT NULL,
  `ReplyID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ReplyID`),
  INDEX `thread_reply_idx` (`ThreadID` ASC),
  INDEX `user_reply_idx` (`UserID` ASC),
  CONSTRAINT `thread_reply`
    FOREIGN KEY (`ThreadID`)
    REFERENCES `lecture_forum`.`threads` (`ThreadID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `user_reply`
    FOREIGN KEY (`UserID`)
    REFERENCES `lecture_forum`.`users` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;

USE `lecture_forum`;

DELIMITER $$
USE `lecture_forum`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `lecture_forum`.`users_AFTER_DELETE`
AFTER DELETE ON `lecture_forum`.`users`
FOR EACH ROW
BEGIN
	delete from threads where userID = old.userID;
    delete from replies where userID = old.userID;
END$$

USE `lecture_forum`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `lecture_forum`.`threads_AFTER_DELETE`
AFTER DELETE ON `lecture_forum`.`threads`
FOR EACH ROW
BEGIN
	delete from replies where threadID = OLD.threadID;
END$$

USE `lecture_forum`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `lecture_forum`.`replies_AFTER_DELETE`
AFTER DELETE ON `lecture_forum`.`replies`
FOR EACH ROW
BEGIN
	update threads a Set a.Replies = a.Replies-1 where a.ThreadID <=> old.ThreadID;
END$$

USE `lecture_forum`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `lecture_forum`.`replies_AFTER_INSERT`
AFTER INSERT ON `lecture_forum`.`replies`
FOR EACH ROW
BEGIN
	update threads a Set a.Replies = a.Replies+1 where a.ThreadID <=> new.ThreadID;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
